# Topic Modeling to Identify Women's Health Concerns on Online Forums
#### Author: Jocelyn Lutes
---
## Project Background

Citizen science is an emerging field of research in which members of the public volunteer to participate in scientific research [(1)](https://www.citizenscience.gov/about/#). One of the most well-known, crowd-sourced citizen science is projects is [American Gut](https://msystems.asm.org/content/3/3/e00031-18), a citizen science project designed to better understand the human microbiome. For this project, citizens interested in contributing to the project paid $99 to receive a sample collection kit and were given instructions to submit the sample [(2)](https://anesthesiology.duke.edu/?p=846744). Within approximately five years, it was estimated that American Gut received samples from over 11,000 people in 45 different countries [(2)](https://anesthesiology.duke.edu/?p=846744), illustrating the willingness of individualas to participate in research and the power of citizen science for generating large datasets that can answer important research questions.

The field of developmental neurotoxicology is interested in understanding the developmental origins of the nervous system throughout the lifespan [(3)](https://www.dntshome.org). Within this field, a substantial amount of research is dedicated to understanding how events that occur during a woman's pregnancy (e.g. illness, treatment with medication, psychological distress, etc.) impact the development of the baby's brain and behavior. Traditional research within the field of maternal health and infant development has relied on maternal report of any events that occurred during pregnancy through regularly-scheduled interviews with a trained research assistant or counselor. Although these interviews provide important information for the studies, the accuracy of reporting depends on the ability of the expecting mother to recall any important events that happened during her pregnancy. 

In order to eliminate any gaps in reporting and to gain a more-representative picture of a woman's pregnancy, we would like to to plan a citizen science project in which women who are interested in participating can download a mobile application that would allow them to log important events during their pregnancy in real time. However, understanding that this will be a large time commitment for participating women, we would also like to provide them with specially curated resources related to women's health concerns. 

## Problem Statement

In order to ensure that any resources that are provided in the application are relevant to potential users, the project leads have proposed that we use an open-ended survey or multiple focus groups to identify several women's health concerns. However, surveys and focus groups can be costly in terms of both time and money, and the project is operating on a limited budget and needs to be completed as quickly as possible. Additionally, it is possible that the small number of women who would be invited to join a focus group or to receive a survey would not be representative of the larger population of women who could opt to particpate in the research. Therefore, the data science team was tasked to uncover an alternate way to identify women's health concerns.

In this project, **I will use natural language processing and unsupervised techniques, such as clustering and topic modeling, to identify women's health concerns from posts in online forums.** Specific concerns will be identified for general women's health, fertility and pregnancy, and postpartum/early parenthood.

## Executive Summary
### Data Collection
Data was collected on August 7, 2020 using the [Pushshift Reddit API](https://github.com/pushshift/api). This API allows for easy aggregation of posts from Reddit.com. For each health domain, data was collected that spanned from August 7, 2020 to February 16, 2019 (a period of approximately 17.5 months).    

**1. General Women's Health Data:**  
* Posts relating to general women's health concerns were collected from [r/WomensHealth](https://www.reddit.com/r/WomensHealth/), [r/obgyn](https://www.reddit.com/r/obgyn/), and [r/thegirlsurvivalguide](https://www.reddit.com/r/TheGirlSurvivalGuide/). 
* This resulted in a total of 31,385 posts from 19,753 unique users.

**2. Fertility and Pregnancy Data:**  
* Posts relating to fertility and pregnancy were collected from [r/TryingForABaby](https://www.reddit.com/r/TryingForABaby/), [r/pregnant](https://www.reddit.com/r/pregnant/), and [r/BabyBumps]https://www.reddit.com/r/BabyBumps/). 
* This resulted in a total of 98,138 posts from 35,127 unique users.

**3. Postpartum and Early Parenthood Data:**
* Posts relating to the postpartum period and early parenthood were collected from [r/beyondthebump](https://www.reddit.com/r/beyondthebump/), [r/postpartumdepression](https://www.reddit.com/r/postpartumdepression/), and [r/breastfeeding](https://www.reddit.com/r/breastfeeding/).
* This resulted in a total of 51,674 posts from 21,585 unique users.

### Data Cleaning and Preprocessing
Once data was in hand, all data was cleaned to check for missing values and inappropriate data types. HTML tags, Reddit-specific tags (e.g. "[removed]", "[deleted]"), URLs, and digits were removed from the text. 

Once the data was cleaned, a custom list of stop words was defined, and posts were lemmatized using ***spaCy***. (Lemmatization refers to the process of reducing a word to its base root.) 

Prior to modeling, a document term matrix was created using the tf-idf vectorizer by ***sklearn***. (Tf-idf creates a bag of words with a weight for each word that is based upon the number of times a word appears in a post and the number of posts that it appears in. If a word appears in many documents, it will receive a low ranking.) If a ***gensim*** model was used, the document term matrix was further processed to create a ***gensim*** corpus. 

### Topic Modeling
NOT YET COMPLETED - I will update this once I have finalized the models. I think that I will most likely have KMeans Clustering and LDA. I might also try Hierarchical Clustering and NNMF.

## Table of Contents

## Imports

In [1]:
# Standard Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Gensim
from gensim import matutils
from gensim import corpora
from gensim.corpora.dictionary import Dictionary
from gensim.models import LsiModel, LdaModel
from gensim.models import CoherenceModel

# NLTK
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords

# pyLDAvis
import pyLDAvis
import pyLDAvis.gensim
pyLDAvis.enable_notebook()

# re
import re

# Scikit Learn
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Scipy
import scipy.sparse


# spaCy
import spacy
nlp = spacy.load('en_core_web_sm')

# Silence Future Warnings
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

## Data

### Read-In Data from CSV

In [2]:
health = pd.read_csv('../data/womens_health.csv', index_col = 'Unnamed: 0')
obsgyn = pd.read_csv('../data/fertility_and_pregnancy.csv', index_col = 'Unnamed: 0')
pospar = pd.read_csv('../data/postpartum.csv', index_col = 'Unnamed: 0')

### Check Head and Shape of Each Data Set
Before cleaning the data, I want to check the head and shape of each data set. This will allow me to see which columns were scraped using the Pushshift API and to assess the size of each data set.

#### General Women's Health Data

In [3]:
health.head(1)

title  \
0  Been to the clinic twice and they don’t know w...   

                                            selftext     subreddit  \
0  So I’ve been having problems with discharge an...  WomensHealth   

   created_utc          author  num_comments  score  is_self   timestamp  
0   1596818251  thecrazedbunny             0      1     True  2020-08-07

In [6]:
health.shape

(31385, 9)

For the general women's health data, before cleaning there are 31,385 posts.

#### Fertility and Pregnancy Data

In [7]:
obsgyn.head(1)

title  \
0  Adding to the kitchen sink approach: I just bo...   

                                            selftext       subreddit  \
0  This time I’m going to be using a menstrual cu...  TryingForABaby   

   created_utc    author  num_comments  score  is_self   timestamp  
0   1596839749  lastput1             7      1     True  2020-08-07

In [9]:
obsgyn.shape

(98138, 9)

Prior to cleaning, the fertility and pregnancy data set has 98,138 posts.

#### Pospartum and Early Parenthood Data

In [10]:
pospar.head(1)

title                                           selftext  \
0  Question about bottles  I'm researching baby bottles and am trying to ...   

   subreddit  created_utc       author  num_comments  score  is_self  \
0  BabyBumps   1596850138  All_Hail_CC             4      1     True   

    timestamp  
0  2020-08-07

In [11]:
pospar.shape

(51674, 9)

Prior to cleaning, the raw postpartum and early parenthood data set has 51,674 rows.

## Data Cleaning

### Combine `title` and `selftext` columns into a `total_text` column

Before beginning to clean the text data, it is important to clean the columns that are included in the data frame. 

The format of a Reddit post consists of a post title (`title`), and there is also an opportunity to write a body of text (`selftext`). For this project, I will be interested in analyzing all text in a post, so I will combine all of the text into a `total_text` column.

#### Function

In [ ]:
def create_total_text(df):
    df['total_text'] = df['title'] + ' ' + df['selftext']
    df.drop(columns = ['title', 'selftext'], inplace = True)
    return df.head(1)

#### Implementation for All Data Sets

In [ ]:
create_total_text(health)
create_total_text(obsgyn)
create_total_text(pospar)

### Drop Unnecessary Columns

For this project, I am interested in using topic modeling to identify areas of concern for each domain of women's health. Therefore, the number of comments and score of each post will not be relevant and will be removed. Because the date is included under `timestamp`, the `created_utc` column will also be removed. The `is_self` column is also not needed and will be removed.

#### Function

In [ ]:
def clean_columns(df):
    df.drop(columns = ['created_utc', 'num_comments', 'score', 'is_self'], inplace = True)

#### Implementation for All Data Sets

In [ ]:
clean_columns(health)
clean_columns(obsgyn)
clean_columns(pospar)

### Check for Null/Missing Values

#### Function

In [ ]:
def display_percent_null(df):
    '''Returns the percent of values in each column that are null or missing'''
    return (df.isna().sum()/len(df)) * 100

#### Implementation for All Data Sets

In [ ]:
display_percent_null(health)

In [ ]:
display_percent_null(obsgyn)

In [ ]:
display_percent_null(pospar)

### Drop Missing Data

Above, we saw that each dataframe is missing some data in the `total_text` column. Because we can not analyze posts without text, any rows with missing data will be removed.

In [ ]:
health.dropna(inplace = True)
obsgyn.dropna(inplace = True)
pospar.dropna(inplace = True)

### Check Data Types

#### Women's Health Data

In [ ]:
health.dtypes

#### Fertility and Pregnancy Data

In [ ]:
obsgyn.dtypes

#### Postpartum Data

In [ ]:
pospar.dtypes

### Convert `Timestamp` column to a datetime object

#### Function

In [ ]:
def convert_to_datetime(df, column):
    df[column] = pd.to_datetime(df[column])
    return df.dtypes

#### Implementation for All Data Sets

In [ ]:
convert_to_datetime(health, 'timestamp')
convert_to_datetime(obsgyn, 'timestamp')
convert_to_datetime(pospar, 'timestamp')

## Text Cleaning
In order to reduce the dimensionality of our text vectors, it is important that only text that will contribute meaning remains in the vector. To do this, we will remove any text that is not believed to contribut meaning to the post.

#### Functions

In [ ]:
def remove_string(df, column, string):
    df[column] = df[column].str.replace(string, '')


def replace_string(df, column, string, replacement):
    df[column] = df[column].str.replace(string, replacement)

#### [removed]
If moderators of the subreddit feel that the post violates one or more of the subreddit's rules, they will remove content of the post and replace it with a "[removed]" tag. Because the [removed] tags will not add any valuable information to the post, these will be removed from posts.

In [ ]:
remove_string(health, 'total_text', '\[removed\]')
remove_string(obsgyn, 'total_text', '\[removed\]')
remove_string(pospar, 'total_text', '\[removed\]')

#### \n
This is a symbol that indicates a new line. Because we are only interested in the text itself, this tag will be removed.

In [ ]:
remove_string(health, 'total_text', '\n')
remove_string(obsgyn, 'total_text', '\n')
remove_string(pospar, 'total_text', '\n')

#### &amp ;

Sometimes, the '&' symbol is not displayed, and the HTML reference `&amp;` shows up instead. This text will be removed.

In [ ]:
remove_string(health, 'total_text', '&amp;')
remove_string(obsgyn, 'total_text', '&amp;')
remove_string(pospar, 'total_text', '&amp;')

#### &gt ;
Some times, the greater than symbol (>) is not properly displayed, and the HTML reference `&gt;` shows up in its place. I will remove this HTML reference.

In [ ]:
remove_string(health, 'total_text', '&gt;')
remove_string(obsgyn, 'total_text', '&gt;')
remove_string(pospar, 'total_text', '&gt;')

#### &lt ;
Some times, the less than symbol (<) is not properly displayed, and the HTML reference `&lt;` shows up in its place. I will remove this HTML reference.

In [ ]:
remove_string(health, 'total_text', '&lt;')
remove_string(obsgyn, 'total_text', '&lt;')
remove_string(pospar, 'total_text', '&lt;')

#### TL;DR
"TL;DR" is an abbreviation that stand for "Too long; Didn't read" and is meant to provide a brief synopsis of the post. Because these letters will not provide any meaningful inormation, they will be removed.

In [ ]:
remove_string(health, 'total_text', 'TL;DR')
remove_string(obsgyn, 'total_text', 'TL;DR')
remove_string(pospar, 'total_text', 'TL;DR')

#### [deleted]

In [ ]:
remove_string(health, 'total_text', 'deleted')
remove_string(obsgyn, 'total_text', 'deleted')
remove_string(pospar, 'total_text', 'deleted')

#### Remove Website URLs

Prior to being able to remove the urls, I will need to reset the indices so that they are in numerical order from 0 to len(data frame). This will allow me to use `.loc` to edit the specific strings in the data frame.

In [ ]:
health.reset_index(drop = True, inplace = True)
obsgyn.reset_index(drop = True, inplace = True)
pospar.reset_index(drop = True, inplace = True)

##### Functions

In [ ]:
def remove_urls(df, column):
    for i in range(0, len(df)):
        df.loc[i, column] = re.sub(r'(https|http)?:\/\/(\w|\.|\/|\?|\=|\&|\%)*\b', '', df.loc[i, column])
        
# Regex Code by Lee Martin (Stack Overflow post)
# https://stackoverflow.com/questions/11331982/how-to-remove-any-url-within-a-string-in-python/11332580        

In [ ]:
def delete_empty_text(df, column):
    df = df[df[column] != '']

##### Remove URLs from all data sets

In [ ]:
remove_urls(health, 'total_text')
remove_urls(obsgyn, 'total_text')
remove_urls(pospar, 'total_text')

##### Check to see if removing URLs resulted in any null 'total_text'; If so, remove it.

In [ ]:
delete_empty_text(health, 'total_text')
delete_empty_text(obsgyn, 'total_text')
delete_empty_text(pospar, 'total_text')

#### Remove Posts by AutoModerator

During EDA, I discovered that several of the subreddits used for data collection have an "AutoModerator" user that makes several posts. Because this user does not represent a woman who is interested in asking a health-related question, I will remove all posts from this user.

##### Functions

In [ ]:
def remove_AutoModerator(df, column):
    df = df[df[column] != 'AutoModerator']
    return df

##### Implementation for all data sets

In [ ]:
health = remove_AutoModerator(health, 'author')
obsgyn = remove_AutoModerator(obsgyn, 'author')
pospar = remove_AutoModerator(pospar, 'author')

#### Remove Digits

##### Function

In [ ]:
def remove_digits(df, column1):
    df[column1] = df[column1].str.replace('[0-9]+', '', regex = True)
    
# https://stackoverflow.com/questions/47010044/how-to-remove-numeric-characters-present-in-countvectorizer

##### Implementation for All Data Sets

In [ ]:
dfs = [health, obsgyn, pospar]

for df in dfs:
    remove_digits(df, 'total_text')

#### Edit "C-section" so that it is not split by the tokenizer

In [ ]:
replace_string(obsgyn, 'total_text', 'c-section', 'csection')
replace_string(obsgyn, 'total_text', 'C-section', 'csection')
replace_string(pospar, 'total_text', 'c-section', 'csection')
replace_string(obsgyn, 'total_text', 'C-section', 'csection')

## Text Preprocessing

## Exploratory Data Analysis

## Model Preparation

## Topic Modeling with Latent Dirichlet Allocation (LDA)

## Topic Interpretation

## Conclusions and Recommendations